// Code generated by MockGen. DO NOT EDIT.
// Source: database.go

// Package repository is a generated GoMock package.
package repository

import (
	item "concurrency/item"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// ReadItems mocks base method.
func (m *MockDatabase) ReadItems() ([]item.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadItems")
	ret0, _ := ret[0].([]item.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadItems indicates an expected call of ReadItems.
func (mr *MockDatabaseMockRecorder) ReadItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadItems", reflect.TypeOf((*MockDatabase)(nil).ReadItems))
}
